### ISSUE TITLE
[FR] Interface to edit db config

### ISSUE THREAD

**Issue by rishavs** [fridgerator/crecto#52]
Crecto should provide an interface where we can define db config elements like poolsize, connection count, retries, timeout etc.

Even if it is provided in the code (and not a separate config file), it will help a lot with dev tasks like data seeding.

**Comment by fridgerator** [comment]
Connection pool stuff is handled by crystal-db via url params you pass to the database url.  Check the params listed in the table on this page under Configuration: https://crystal-lang.org/docs/database/connection_pool.html

I've thought about providing a separate configuration for crecto, but using the method above is already pretty easy so I haven't made up my mind yet.

**Comment by fridgerator** [comment]
Working on a change right now so `Repo` works how ecto does, something I should have done to begin with but missed.

Now the user defines their own Repo to use, instead of calling `Crecto::Repo`.  Inside the repo is where your database connection configuration goes.  This will also allow for an application to use multiple data sources, which currently wont work.

Repo definitions look like:

```crystal
module Repo
  extend Crecto::Repo

  config do |conf|
    conf.adapter = Crecto::Adapters::Postgres
    conf.database = "crecto_test"
    conf.username = "test"
    conf.password = "123"
    conf.hostname = "localhost"
    conf.port = 5432
  end
end

module MysqlRepo
  extend Crecto::Repo

  config.do |conf|
    conf.adapter = Crecto::Adapters::Mysql
    conf.database = "mysql_test"
    conf.port = 3306
  end
end

# Then use it in your application like normal:
Repo.insert(user)
MysqlRepo.insert(user)
```

The branch is [repo_config](https://github.com/fridgerator/crecto/tree/repo_config), ([diff link](https://github.com/fridgerator/crecto/compare/master...repo_config)).

Branch is working, but is still a WIP.  One thing in particular I'd like to figure out a better way to do is: Right now I'm passing the connection (or transaction connection) around through several methods so that by the time it gets to `execute` in the adapter it has the connection.

Tagging you all because you've been contributing or using crecto the most lately, and this will definitely be a breaking change.

@Zhomart @neovintage @metacortex @huacnlee @jipiboily
